-- MySQL Script generated by MySQL Workbench
-- Thu Jan 11 21:48:10 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb2` DEFAULT CHARACTER SET utf8 ;
USE `mydb2` ;

-- -----------------------------------------------------
-- Table `mydb2`.`Lectures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`Lectures` (
  `idLectures` INT NOT NULL,
  `Email` VARCHAR(45) NULL,
  `LectureName` VARCHAR(50) NULL,
  `PhoneNumber` INT NULL,
  `Address` VARCHAR(45) NULL,
  `DOB` DATE NULL,
  PRIMARY KEY (`idLectures`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`TrainingDepartment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`TrainingDepartment` (
  `idTrainingDepartment` INT NOT NULL,
  `PhoneNumber` INT NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`idTrainingDepartment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`Subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`Subject` (
  `idSubject` INT NOT NULL,
  `SubjectName` VARCHAR(45) NULL,
  `TraingDepartmentId` INT NULL,
  PRIMARY KEY (`idSubject`),
  INDEX `TrainingDepartment_idx` (`TraingDepartmentId` ASC) VISIBLE,
  CONSTRAINT `TrainingDepartmentId`
    FOREIGN KEY (`TraingDepartmentId`)
    REFERENCES `mydb2`.`TrainingDepartment` (`idTrainingDepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`Class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`Class` (
  `idClass` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `StartDate` DATE NULL,
  `EndDate` DATE NULL,
  `TrainingDeapartmentId` INT NULL,
  PRIMARY KEY (`idClass`),
  INDEX `TrainingDepartmentId_idx` (`TrainingDeapartmentId` ASC) VISIBLE,
  CONSTRAINT `TrainingDepartmentId9`
    FOREIGN KEY (`TrainingDeapartmentId`)
    REFERENCES `mydb2`.`TrainingDepartment` (`idTrainingDepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`Lecture Asignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`Lecture Asignment` (
  `idLecture Asignment` INT NOT NULL,
  `LectureId` INT NULL,
  `ClassId` INT NULL,
  PRIMARY KEY (`idLecture Asignment`),
  INDEX `LectureId_idx` (`LectureId` ASC) VISIBLE,
  INDEX `ClassId_idx` (`ClassId` ASC) VISIBLE,
  CONSTRAINT `LectureId`
    FOREIGN KEY (`LectureId`)
    REFERENCES `mydb2`.`Lectures` (`idLectures`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ClassId`
    FOREIGN KEY (`ClassId`)
    REFERENCES `mydb2`.`Class` (`idClass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`Students` (
  `idStudents` INT NOT NULL,
  `Email` VARCHAR(45) NULL,
  `ClassId` INT NULL,
  `PhoneNumber` INT NULL,
  `Address` VARCHAR(45) NULL,
  `DOB` DATE NULL,
  `TrainingDId` INT NULL,
  PRIMARY KEY (`idStudents`),
  INDEX `ClassId_idx` (`ClassId` ASC) VISIBLE,
  INDEX `TraininDId_idx` (`TrainingDId` ASC) VISIBLE,
  CONSTRAINT `ClassId4`
    FOREIGN KEY (`ClassId`)
    REFERENCES `mydb2`.`Class` (`idClass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TraininDId`
    FOREIGN KEY (`TrainingDId`)
    REFERENCES `mydb2`.`TrainingDepartment` (`idTrainingDepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`Semester`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`Semester` (
  `idSemester` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`idSemester`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`Register`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`Register` (
  `idRegister` INT NOT NULL,
  `StudentId` INT NULL,
  `SubjectId` INT NULL,
  `SemesterId` INT NULL,
  `Grade` FLOAT NULL,
  PRIMARY KEY (`idRegister`),
  INDEX `Studentid_idx` (`StudentId` ASC) VISIBLE,
  INDEX `subjectid_idx` (`SubjectId` ASC) VISIBLE,
  INDEX `Semesterid_idx` (`SemesterId` ASC) VISIBLE,
  CONSTRAINT `Studentid`
    FOREIGN KEY (`StudentId`)
    REFERENCES `mydb2`.`Students` (`idStudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `subjectid`
    FOREIGN KEY (`SubjectId`)
    REFERENCES `mydb2`.`Subject` (`idSubject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Semesterid`
    FOREIGN KEY (`SemesterId`)
    REFERENCES `mydb2`.`Semester` (`idSemester`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`FeedBack`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`FeedBack` (
  `idFeedBack` INT NOT NULL,
  `StudentId` INT NULL,
  `LectureId` INT NULL,
  `Content` VARCHAR(45) NULL,
  `Date` DATE NULL,
  PRIMARY KEY (`idFeedBack`),
  INDEX `StudentId_idx` (`StudentId` ASC) VISIBLE,
  INDEX `lectureid_idx` (`LectureId` ASC) VISIBLE,
  CONSTRAINT `StudentId5`
    FOREIGN KEY (`StudentId`)
    REFERENCES `mydb2`.`Students` (`idStudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `lectureid4`
    FOREIGN KEY (`LectureId`)
    REFERENCES `mydb2`.`Lectures` (`idLectures`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`Parent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`Parent` (
  `idParent` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Pass` VARCHAR(45) NULL,
  `Username` VARCHAR(45) NULL,
  `Job` VARCHAR(45) NULL,
  `PlaceOfWork` VARCHAR(45) NULL,
  `Studentid` INT NULL,
  PRIMARY KEY (`idParent`),
  INDEX `StudentId_idx` (`Studentid` ASC) VISIBLE,
  CONSTRAINT `StudentId6`
    FOREIGN KEY (`Studentid`)
    REFERENCES `mydb2`.`Students` (`idStudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`Notice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`Notice` (
  `idNotice` INT NOT NULL,
  `Status` VARCHAR(45) NULL,
  `StudentId` INT NULL,
  `LectureId` INT NULL,
  `ParentId` INT NULL,
  `trainingDId` INT NULL,
  `Date` DATE NULL,
  `Content` VARCHAR(45) NULL,
  PRIMARY KEY (`idNotice`),
  INDEX `Student_idx` (`StudentId` ASC) VISIBLE,
  INDEX `Lecture_idx` (`LectureId` ASC) VISIBLE,
  INDEX `Parent_idx` (`ParentId` ASC) VISIBLE,
  INDEX `Training_idx` (`trainingDId` ASC) VISIBLE,
  CONSTRAINT `Student`
    FOREIGN KEY (`StudentId`)
    REFERENCES `mydb2`.`Students` (`idStudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Lecture`
    FOREIGN KEY (`LectureId`)
    REFERENCES `mydb2`.`Lectures` (`idLectures`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Parent`
    FOREIGN KEY (`ParentId`)
    REFERENCES `mydb2`.`Parent` (`idParent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Training`
    FOREIGN KEY (`trainingDId`)
    REFERENCES `mydb2`.`TrainingDepartment` (`idTrainingDepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`ClassSession`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`ClassSession` (
  `idClassSession` INT NOT NULL,
  `LectureId` INT NULL,
  `ClassId` INT NULL,
  `Date` DATE NULL,
  `AttendenceTaken` BIT NULL,
  PRIMARY KEY (`idClassSession`),
  INDEX `Lecture_idx` (`LectureId` ASC) VISIBLE,
  INDEX `Class_idx` (`ClassId` ASC) VISIBLE,
  CONSTRAINT `Lectu3re`
    FOREIGN KEY (`LectureId`)
    REFERENCES `mydb2`.`Lectures` (`idLectures`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Class`
    FOREIGN KEY (`ClassId`)
    REFERENCES `mydb2`.`Class` (`idClass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`Attendence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`Attendence` (
  `idAttendence` INT NOT NULL,
  `StudentId` INT NULL,
  `ClassSessionid` INT NULL,
  `Status` VARCHAR(45) NULL,
  PRIMARY KEY (`idAttendence`),
  INDEX `Student_idx` (`StudentId` ASC) VISIBLE,
  INDEX `ClassSess_idx` (`ClassSessionid` ASC) VISIBLE,
  CONSTRAINT `Studen5t`
    FOREIGN KEY (`StudentId`)
    REFERENCES `mydb2`.`Students` (`idStudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ClassSess`
    FOREIGN KEY (`ClassSessionid`)
    REFERENCES `mydb2`.`ClassSession` (`idClassSession`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`Enroll`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`Enroll` (
  `Studentid` INT NOT NULL,
  `ClassId` INT NOT NULL,
  `EnrollId` INT NOT NULL,
  INDEX `student_idx` (`ClassId` ASC) VISIBLE,
  PRIMARY KEY (`EnrollId`),
  CONSTRAINT `clas7s`
    FOREIGN KEY (`Studentid`)
    REFERENCES `mydb2`.`Class` (`idClass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `stude8nt`
    FOREIGN KEY (`ClassId`)
    REFERENCES `mydb2`.`Students` (`idStudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`SubjectInstructure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`SubjectInstructure` (
  `LectureId` INT NOT NULL,
  `SubjectId` INT NOT NULL,
  `SubjectInstructureId` INT NOT NULL,
  INDEX `Subject_idx` (`SubjectId` ASC) VISIBLE,
  PRIMARY KEY (`SubjectInstructureId`),
  CONSTRAINT `Lecture09`
    FOREIGN KEY (`LectureId`)
    REFERENCES `mydb2`.`Lectures` (`idLectures`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Subject`
    FOREIGN KEY (`SubjectId`)
    REFERENCES `mydb2`.`Subject` (`idSubject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb2`.`Admin` (
  `idAdmin` INT NOT NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
