
-- MySQL Script generated by MySQL Workbench
-- Thu Jan 11 21:48:10 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb36
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb36
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb36` DEFAULT CHARACTER SET utf8 ;
USE `mydb36` ;

-- -----------------------------------------------------
-- Table `mydb36`.`Lectures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb36`.`Lectures` (
  `idLectures` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(45) NULL,
  `LectureName` VARCHAR(50) NULL,
  `PhoneNumber` INT NULL,
  `Address` VARCHAR(45) NULL,
  `DOB` DATE NULL,
  PRIMARY KEY (`idLectures`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb36`.`TrainingDepartment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb36`.`TrainingDepartment` (
  `idTrainingDepartment` INT NOT NULL AUTO_INCREMENT,
  `PhoneNumber` INT NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`idTrainingDepartment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb36`.`Subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb36`.`Subject` (
  `idSubject` INT NOT NULL AUTO_INCREMENT,
  `SubjectName` VARCHAR(45) NULL,
  `TraingDepartmentId` INT NULL,
  PRIMARY KEY (`idSubject`),
  INDEX `TrainingDepartment_idx` (`TraingDepartmentId` ASC) VISIBLE,
  CONSTRAINT `TrainingDepartmentId`
    FOREIGN KEY (`TraingDepartmentId`)
    REFERENCES `mydb36`.`TrainingDepartment` (`idTrainingDepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb36`.`Class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb36`.`Class` (
  `idClass` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `StartDate` DATE NULL,
  `EndDate` DATE NULL,
  `TrainingDeapartmentId` INT NULL,
  `idSubject` int null,
  PRIMARY KEY (`idClass`),
  INDEX `TrainingDepartmentId_idx` (`TrainingDeapartmentId` ASC) VISIBLE,
    INDEX `Subject_idx` (`idSubject` ASC) VISIBLE,
  CONSTRAINT `TrainingDepartmentId9`
    FOREIGN KEY (`TrainingDeapartmentId`)
    REFERENCES `mydb36`.`TrainingDepartment` (`idTrainingDepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
constraint `Subject0`
     FOREIGN KEY (`idSubject`)
  REFERENCES `mydb36`.`Subject` (`idSubject`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb36`.`Lecture Asignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb36`.`LectureAsignment` (
  `idLecture Asignment` INT NOT NULL AUTO_INCREMENT,
  `LectureId` INT NULL,
  `ClassId` INT NULL,
  PRIMARY KEY (`idLecture Asignment`),
  INDEX `LectureId_idx` (`LectureId` ASC) VISIBLE,
  INDEX `ClassId_idx` (`ClassId` ASC) VISIBLE,
  CONSTRAINT `LectureId`
    FOREIGN KEY (`LectureId`)
    REFERENCES `mydb36`.`Lectures` (`idLectures`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ClassId`
    FOREIGN KEY (`ClassId`)
    REFERENCES `mydb36`.`Class` (`idClass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb36`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb36`.`Students` (
  `idStudents` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(45) NULL,
  `ClassId` INT NULL,
  `PhoneNumber` INT NULL,
  `Address` VARCHAR(45) NULL,
  `DOB` DATE NULL,
  `TrainingDId` INT NULL,
  `ParentId2` INT,
  PRIMARY KEY (`idStudents`),
  INDEX `ClassId_idx` (`ClassId` ASC) VISIBLE,
  INDEX `TraininDId_idx` (`TrainingDId` ASC) VISIBLE,
  INDEX `ParentId2_idx` (`ParentId2` ASC) VISIBLE,
  CONSTRAINT `TraininDId`
    FOREIGN KEY (`TrainingDId`)
    REFERENCES `mydb36`.`TrainingDepartment` (`idTrainingDepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ParentId`
    FOREIGN KEY (`ParentId2`)
    REFERENCES `mydb36`.`Parent` (`idParent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `mydb36`.`Semester`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb36`.`Semester` (
  `idSemester` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`idSemester`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb36`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb36`.`Department` (
  `did` INT NOT NULL AUTO_INCREMENT,
  `idSemester` INT NULL,
  `dname` VARCHAR(45) NULL,
  PRIMARY KEY (`did`),
  INDEX `Semester_idx` (`idSemester` ASC) VISIBLE,
  CONSTRAINT `SemesterId_Department`
    FOREIGN KEY (`idSemester`)
    REFERENCES `mydb36`.`Semester` (`idSemester`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb36`.`Register`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb36`.`Register` (
  `idRegister` INT NOT NULL AUTO_INCREMENT,
  `StudentId` INT NULL,
  `SubjectId` INT NULL,
  `SemesterId` INT NULL,
  `Grade` FLOAT NULL,
  PRIMARY KEY (`idRegister`),
  INDEX `Studentid_idx` (`StudentId` ASC) VISIBLE,
  INDEX `subjectid_idx` (`SubjectId` ASC) VISIBLE,
  INDEX `Semesterid_idx` (`SemesterId` ASC) VISIBLE,
  CONSTRAINT `Studentid`
    FOREIGN KEY (`StudentId`)
    REFERENCES `mydb36`.`Students` (`idStudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `subjectid10`
    FOREIGN KEY (`SubjectId`)
    REFERENCES `mydb36`.`Subject` (`idSubject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Semesterid10`
    FOREIGN KEY (`SemesterId`)
    REFERENCES `mydb36`.`Semester` (`idSemester`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb36`.`FeedBack`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb36`.`FeedBack` (
  `idFeedBack` INT NOT NULL AUTO_INCREMENT,
  `StudentId` INT NULL,
  `LectureId` INT NULL,
  `Content` VARCHAR(45) NULL,
  `Date` DATE NULL,
  PRIMARY KEY (`idFeedBack`),
  INDEX `StudentId_idx` (`StudentId` ASC) VISIBLE,
  INDEX `lectureid_idx` (`LectureId` ASC) VISIBLE,
  CONSTRAINT `StudentId5`
    FOREIGN KEY (`StudentId`)
    REFERENCES `mydb36`.`Students` (`idStudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `lectureid4`
    FOREIGN KEY (`LectureId`)
    REFERENCES `mydb36`.`Lectures` (`idLectures`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb36`.`Parent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb36`.`Parent` (
  `idParent` INT NOT NULL AUTO_INCREMENT,
  `Name` NVARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Pass` VARCHAR(45) NULL,
  `Username` VARCHAR(45) NULL,
  `Job` VARCHAR(45) NULL,
  `PlaceOfWork` VARCHAR(45) NULL,
  PRIMARY KEY (`idParent`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb36`.`Notice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb36`.`Notice` (
  `idNotice` INT NOT NULL AUTO_INCREMENT,
  `Status` VARCHAR(45) NULL,
  `StudentId` INT NULL,
  `LectureId` INT NULL,
  `ParentId` INT NULL,
  `trainingDId` INT NULL,
  `Date` DATE NULL,
  `Content` VARCHAR(45) NULL,
  PRIMARY KEY (`idNotice`),
  INDEX `Student_idx` (`StudentId` ASC) VISIBLE,
  INDEX `Lecture_idx` (`LectureId` ASC) VISIBLE,
  INDEX `Parent_idx` (`ParentId` ASC) VISIBLE,
  INDEX `Training_idx` (`trainingDId` ASC) VISIBLE,
  CONSTRAINT `Student`
    FOREIGN KEY (`StudentId`)
    REFERENCES `mydb36`.`Students` (`idStudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Lecture`
    FOREIGN KEY (`LectureId`)
    REFERENCES `mydb36`.`Lectures` (`idLectures`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Parent`
    FOREIGN KEY (`ParentId`)
    REFERENCES `mydb36`.`Parent` (`idParent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Training`
    FOREIGN KEY (`trainingDId`)
    REFERENCES `mydb36`.`TrainingDepartment` (`idTrainingDepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb36`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb36`.`Room` (
  `rid` INT NOT NULL AUTO_INCREMENT,
  `rname` VARCHAR(45) NULL,
  PRIMARY KEY (`rid`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb36`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb36`.`TimeSlot` (
  `tid` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`tid`)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `mydb36`.`ClassSession`

CREATE TABLE IF NOT EXISTS `mydb36`.`ClassSession` (
  `idClassSession` INT NOT NULL AUTO_INCREMENT,
  `LectureId` INT ,
  `ClassId` INT NULL,
  `rid` INT NULL,
  `tid` INT NULL, -- Thêm cột `tid`
  `Date` DATE NULL,
  `Status` BIT NULL,
  PRIMARY KEY (`idClassSession`),
  INDEX `Lecture_idx` (`LectureId` ASC) VISIBLE,
  INDEX `Class_idx` (`ClassId` ASC) VISIBLE,
  INDEX `Room_idx` (`rid` ASC) VISIBLE,
  INDEX `TimeSlot_idx` (`tid` ASC) VISIBLE, -- Thêm index cho cột `tid`
  CONSTRAINT `Lectu3re`
    FOREIGN KEY (`LectureId`)
    REFERENCES `mydb36`.`Lectures` (`idLectures`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Class`
    FOREIGN KEY (`ClassId`)
    REFERENCES `mydb36`.`Class` (`idClass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Room`
    FOREIGN KEY (`rid`)
    REFERENCES `mydb36`.`Room` (`rid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TimeSlot` -- Tạo ràng buộc khóa phụ cho cột `tid`
    FOREIGN KEY (`tid`)
    REFERENCES `mydb36`.`TimeSlot` (`tid`) -- Thay `TimeSlot` bằng tên bảng giáo viên thực tế
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `mydb36`.`Attendence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb36`.`Attendence` (
  `idAttendence` INT NOT NULL AUTO_INCREMENT,
  `StudentId` INT NULL,
  `ClassSessionid` INT NULL,
  `Status` VARCHAR(45) NULL,
  PRIMARY KEY (`idAttendence`),
  INDEX `Student_idx` (`StudentId` ASC) VISIBLE,
  INDEX `ClassSess_idx` (`ClassSessionid` ASC) VISIBLE,
  CONSTRAINT `Studen5t`
    FOREIGN KEY (`StudentId`)
    REFERENCES `mydb36`.`Students` (`idStudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ClassSess`
    FOREIGN KEY (`ClassSessionid`)
    REFERENCES `mydb36`.`ClassSession` (`idClassSession`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb36`.`Enroll`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb36`.`Enroll` (
  `Studentid` INT NOT NULL ,
  `ClassId` INT NOT NULL,
  `EnrollId` INT NOT NULL AUTO_INCREMENT,
  INDEX `student_idx` (`ClassId` ASC) VISIBLE,
  PRIMARY KEY (`EnrollId`),
  CONSTRAINT `clas7s`
    FOREIGN KEY (`Studentid`)
    REFERENCES `mydb36`.`Class` (`idClass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `stude8nt`
    FOREIGN KEY (`ClassId`)
    REFERENCES `mydb36`.`Students` (`idStudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb36`.`SubjectInstructure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb36`.`SubjectInstructure` (
  `LectureId` INT NOT NULL ,
  `SubjectId` INT NOT NULL,
  `SubjectInstructureId` INT NOT NULL AUTO_INCREMENT,
  INDEX `Subject_idx` (`SubjectId` ASC) VISIBLE,
  PRIMARY KEY (`SubjectInstructureId`),
  CONSTRAINT `Lecture09`
    FOREIGN KEY (`LectureId`)
    REFERENCES `mydb36`.`Lectures` (`idLectures`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Subject`
    FOREIGN KEY (`SubjectId`)
    REFERENCES `mydb36`.`Subject` (`idSubject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb36`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb36`.`Admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Thêm dữ liệu cho bảng `Lectures`
INSERT INTO `mydb36`.`Lectures` (`Email`, `LectureName`, `PhoneNumber`, `Address`, `DOB`) 
VALUES 
  ('lecture1@gmail.com', 'John Doe', 0376409623, '123 Main St', '1990-01-01'),
  ('lecture2@gmail.com', 'Jane Smith', 0376409612,'456 Oak St', '1985-05-15'),
  ('lecture3@gmail.com', 'Bob Johnson', 0376409423, '789 Pine St', '1980-10-20');

-- Thêm dữ liệu cho bảng `TrainingDepartment`
INSERT INTO `mydb36`.`TrainingDepartment` (`PhoneNumber`, `Email`)
VALUES 
  (0376409345, 'training@gmail.com'),
  (0376409345, 'training2@gmail.com');

-- Thêm dữ liệu cho bảng `Subject`
INSERT INTO Subject (`SubjectName`, `TraingDepartmentId`)
VALUES 
  ('PRJ311', 1), 
  ('PRO192', 2);

-- Thêm dữ liệu cho bảng `Class`
INSERT INTO `mydb36`.`Class` (`Name`, `StartDate`, `EndDate`, `TrainingDeapartmentId`,`idSubject`)
VALUES 
  ('ClassA', '2024-01-01', '2024-06-30', 1,1),
  ('ClassB', '2024-02-01', '2024-07-31', 2,2);

-- Thêm dữ liệu cho bảng `Lecture Asignment`
INSERT INTO `mydb36`.`LectureAsignment` (`LectureId`, `ClassId`)
VALUES 
  (1, 1),
  (2, 2);
-- Thêm dữ liệu cho bảng `Parent`
INSERT INTO `mydb36`.`Parent` (`Name`, `Address`, `Email`, `Pass`, `Username`, `Job`, `PlaceOfWork`)
VALUES 
  ('ParentA', '789 Pine St', 'parent1@gmail.com', 'password', 'parent_user', 'Parent Job', 'Workplace'),
  ('ParentB', '456 Oak St', 'parent2@gmail.com', 'password', 'parent_user2', 'Parent Job', 'Workplace');
-- Thêm dữ liệu cho bảng `Students`
INSERT INTO `mydb36`.`Students` ( `Email`, `ClassId`, `PhoneNumber`, `Address`, `DOB`, `TrainingDId`, `ParentId2`)
VALUES 
  ( 'trunghieu2003hhh@gmail.com', 1, 0376409962, '36 Oak St', '2000-01-02', 1, 1),
  ( 'student5@gmail.com', 2, 0376409136, '89 Pine St', '1999-05-05', 2, 2);
Select * From `Students`;
-- Thêm dữ liệu cho bảng `Semester`
INSERT INTO `mydb36`.`Semester` (`Name`)
VALUES 
  ('Spring 2024'),
  ('Fall 2024');

-- Thêm dữ liệu cho bảng `Register`
INSERT INTO `mydb36`.`Register` (`StudentId`, `SubjectId`, `SemesterId`, `Grade`)
VALUES 
  (1, 1, 1, 85.5),
  (2, 2, 2, 90.0);

-- Thêm dữ liệu cho bảng `FeedBack`
INSERT INTO `mydb36`.`FeedBack` (`StudentId`, `LectureId`, `Content`, `Date`)
VALUES 
  (1, 1, 'Good lecture!', '2024-02-15'),
  (2, 2, 'Very informative!', '2024-03-10');



-- Thêm dữ liệu cho bảng `Notice`
INSERT INTO `mydb36`.`Notice` (`Status`, `StudentId`, `LectureId`, `ParentId`, `trainingDId`, `Date`, `Content`)
VALUES 
  ('Published', 1, 1, 1, 1, '2024-03-01', 'Important notice about upcoming events.'),
  ('Draft', 2, 2, 2, 2, '2024-03-05', 'Upcoming parent-teacher meeting.');

-- Thêm dữ liệu cho bảng `ClassSession`
INSERT INTO `mydb36`.`Room` (`rname`)
VALUES 
  ('RoomA'),
  ('RoomB');

-- Thêm dữ liệu cho bảng `TimeSlot`
INSERT INTO `mydb36`.`TimeSlot` (`description`)
VALUES 
  ('Morning'),
  ('Afternoon');

-- Thêm dữ liệu cho bảng `ClassSession`
INSERT INTO `mydb36`.`ClassSession` (`LectureId`, `ClassId`, `rid`, `tid`, `Date`, `Status`)
VALUES 
  (1, 1, 1, 1, '2024-02-01', 1),
  (2, 2, 2, 2, '2024-02-05', 0);

-- Thêm dữ liệu cho bảng `Attendence`
INSERT INTO `mydb36`.`Attendence` (`StudentId`, `ClassSessionid`, `Status`)
VALUES 
  (1, 1, 'Attend'),
  (2, 2, 'Absent');

-- Thêm dữ liệu cho bảng `Enroll`
INSERT INTO `mydb36`.`Enroll` (`Studentid`, `ClassId`)
VALUES 
  (1, 1),
  (2, 2);

-- Thêm dữ liệu cho bảng `SubjectInstructure`
INSERT INTO `mydb36`.`SubjectInstructure` (`LectureId`, `SubjectId`)
VALUES 
  (1, 1),
  (2, 2);

-- Thêm dữ liệu cho bảng `Admin`
INSERT INTO `mydb36`.`Admin` (`Email`)
VALUES 
  ('admin@gmail.com'),
  ('admin2@gmail.com');
ALTER TABLE mydb36.parent ADD COLUMN otp_sent BOOLEAN DEFAULT FALSE;
SELECT * FROM ClassSession WHERE idClassSession = 1;
SELECT 
    cs.idClassSession,
    cs.Date,
    cs.Status,
    c.idClass,
    c.Name AS ClassName,
    c.StartDate, 
    c.EndDate,
    s.idSubject,
    s.SubjectName,
    r.rid,
    r.rname, 
    t.tid,
    t.description
FROM
    ClassSession cs
        INNER JOIN
    Class c ON cs.ClassId = c.idClass
    INNER JOIN 
    Subject s ON s.idSubject = c.idSubject
        INNER JOIN
    Room r ON cs.rid = r.rid
        INNER JOIN
    TimeSlot t ON cs.tid = t.tid
WHERE
    cs.LectureId = 1;
    
Select * From Class c INNER JOIN Subject s ON s.idSubject = c.idSubject